### ISSUE TITLE
Upgrade to Plone 5.0

### ISSUE THREAD

**Issue by potzenheimer** [a25kk/hfph#17]
We need to update the infrastructure to Plone 5.0

Possible caveats:

- toolbar integration (add condition to rules.xml)
- custom widget assignments in content types (could be left broken)
- prevent javascript issues for authenticated users
- update password field support

Issues:

- [x] collective.embedly (CMFDefault Importe)
- [x] collective.easyform (unreleased fixes)
- [x] collective.emaillogin4 (remove from database)
- [x] plone.app.widgets (remove from database)

**Comment by potzenheimer** [comment]
Staging branch wurde gestartet, um die Integration und das Update zu testen.

**Comment by potzenheimer** [comment]
Plone 5.0rc1 update mit aktualisiertem Site Theme

**Comment by potzenheimer** [comment]
Zwischenversion 4.3.6 upgrade druchgeführt und deployed. Damit sollten wir mit sauberen Packages starten und können lokal die PLone 5.0 migration testen.

**Comment by bumblebee831** [comment]
Super!

**Comment by potzenheimer** [comment]
Plone now running Version 5.0.3 pending.

**Comment by potzenheimer** [comment]
Wie ist hier der Stand bzgl easyform? Kann das Ticket an dieser Stelle geschlossen werden?
