### ISSUE TITLE
Shibboleth

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/hfph#2]
Bitte um Stellungnahme zur E-Mail (Kommentar unten)

**Comment by bumblebee831** [comment]
E-Mail vom LRZ an Julia:

Hallo Frau Krumme,

Frau Haarer hat mir Ihre Anfrage bzgl. Moodle/Shibboleth weitergeleitet.

Moodle können Sie auf unseren Webservern im Rahmen des Webhostings
(http://www.lrz.de/services/netzdienste/www/webserver/) installieren und
nutzen. Wir können Ihnen in diesem Fall anbieten, dafür auch den nötigen
Shibboleth-Service-Provider aufzusetzen.

Falls auch die Authentifizierung am Hochschulportal (auf Ihrer am LRZ
gehosteten VM) über Shibboleth laufen soll muss dort ebenfalls ein
Shibboleth-Service-Provider betrieben werden, und die Applikation muss die
entsprechende Schnittstelle zur Verfügung stellen. Für diesen Teil sind Sie
selbst verantwortlich.

Weiterhin benötigen Sie einen Shibboleth-Identity-Provider. Diesen müssen
Sie selbst mit den Daten der Nutzer befüllen, den Betrieb davon übernimmt
das LRZ nicht, es gibt aber die Möglichkeit das Angebot des DFN in Anspruch
zu nehmen, siehe https://www.aai.dfn.de/der-dienst/ausgelagerter-idp/

Voraussetzung ist, dass:

1. die Einrichtung (also die HfPh) einen Rahmenvertrag mit dem DFN hat oder
schließt und

2. die Einrichtung ein Identity-Management-System in irgendeiner Form haben
muss (LDAP-Server oder SQL-Datenbank), die der IdP als Datenbasis verwenden
kann.

Falls Sie weitere Fragen haben können Sie mich gerne kontaktieren.

Viele Grüße
Ulrike Kirchgesser

**Comment by potzenheimer** [comment]
1. für diese Art von "Aufgabe" ist wohl Github das falsche Medium, weil wir hier näher bei "bitte spülmaschine ausräumen" als bei "fix login error" - also eher ein *soft task* ;)
2. wir sind der falsche Ansprechpartner für diese E-Mail. Was wir machen würden, ist einen Konsumer für einen externen Auth Provider erstellen (im Portal und per installation in moodle), d.h. ermöglichen, dass man sich via eines zentralen Authentifizierungsanbieters anmelden/einloggen kann. Mit dem Setup und der Implementierung bzw Planung kann und will ich mich nicht beschäftigen.

**Comment by bumblebee831** [comment]
zu 1. Also ich weiß nicht. Es gibt extra ein Label "questions". Und wenn ich alle Tasks nach Ihrer Gewichtung einschätze, die jeder von uns natürlich anders sieht, und danach einem entsprechenden Tool zuweise (wobei wir momentan nicht mal alles abdecken können), verliert hier jeder den Überblick und ich werde nicht mehr fertig...
zu 2. Ihre Frage war, ob wir ihr die E-Mail übersetzen könnten, da sie diese nicht versteht. Also im Klartext: Ist das ok, was die da vorschlagen oder nicht? Gibt es irgendetwas, das unserer Installation und unseren Plänen widerspricht. Ich selbst, verstehe die E-Mail auch nicht und kann sie daher nicht einschätzen.

**Comment by potzenheimer** [comment]
Ich habe ja schon gesagt: die gemeinsame Bestandsaufnahme zu unserer internen Orginisation ist überfällig. Ich bin mittlerweile davon überzeugt, dass wir es nicht schaffen werden *ein* tool zu finden, mit dem das komplexe Spektrum von "Multiprojekt Agentur" abgedeckt werden kann.

Zur Frage:
Ich habe ganz ehrlich keinen blassen Schimmer, was diese E-Mail bedeuten soll - mal ganz abgesheen davon, dass mich/uns maximal 10% der letzendlichen Implementierung überhaupt etwas angehen würden. Ich kann nur sagen/wiederholen, was von unserer Seite vorstellbar wäre (siehe letzter Kommentar), beurteilen kann ich diesen sehr unverständlich formulierten Quatsch leider nicht.
