### ISSUE TITLE
Responsible Person Asignment View

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/hfph#3]
As admin user I want a standalone view to select the responsibel user for the given context

**given**: Logged in as staff member
**when**: opening the target context
**then**: Asignment view provided by system

## Implementierung:

- [x] Storage für "worklist" (zugeweisene Inhalte, für die ein bestimmter User verantwortlich ist)
- [x] @@asignment-view: UID-Storage befüllen und automatische Vergabe der benötigten Zugriffsrechte

**Comment by potzenheimer** [comment]
Die Basisanwendung **@@asignment-view** wurde implementiert. Nun muss noch ein Handler zur Zuweisung der Zugriffsrechte und die entsprechenden Implementierung im User Workspace erfolgen

**Comment by potzenheimer** [comment]
So das könnte bereits getestet werden. Die Frage nachd er Asignment voew stellt sich jetzt allerdings noch - also, wo wir die view bereitstellen wollen. Ich wäre für die Toolbar: rechts neben *Freigabe*  eine Action *Verantwortlicher*

**Comment by bumblebee831** [comment]
Wie soll ich das testen? Soll Julia testen? Wir müssen eh noch auf die Einbindung in die Toolbar warten, oder? "Verantwortlicher" finde ich gut.

**Comment by potzenheimer** [comment]
Man könnte bereits bei beliebigem Inhalt `@@asignment-view` öffnen und das mal durchspielen.  Ansonsten gibt es noch keine UI Integration das ist richtig.

**Comment by bumblebee831** [comment]
Ok. Getestet wird am Montag. Ich erreiche Julia nicht mehr und ich würde gerne mit Ihr den Test anhand eines Lehrenden durchführen. Ich möchte keine Verwirrung in der Hochschule und daher vorher mit ihr reden.

**Comment by bumblebee831** [comment]
Zuweisung funktioniert noch nicht: https://www.hfph.de/studium/lehrveranstaltungen/philosophie-des-geistes/@@asignment/9995712cf8e24234bebac42f3d08ac5e/asign
(Log entry not found or expired)

**Comment by potzenheimer** [comment]
Ok - da haben wir einen Bug in *plone.api*: das Problem wurde bereits erkannt und gefixed, allerdings gibt es noch kein neues Release: https://github.com/plone/plone.api/commit/d8ab6deb28dc98a77f15ab204cb4d1e28b6c087a

Nun haben wir mal wieder die Wahl:

1. verwenden eines Github code checkouts mit dem aktuellen Master (pro: problem gefixt, cons: eventuell noch unentdeckte andere Probleme enthalten)

2. wir warten auf ein neue *plone.api* release und verwenden einstweilen die "low level" API aus ZOPE - dazu muss ich allerdings den Code umschreiben und erstmal nachsehen, da das Local Role management auch bereits über ein Jahrzehnt auf dem Buckel haben dürfte ;)
