### ISSUE TITLE
Integration dynamisches Listing von Drittmittelprojekten via XHR call

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/hfph#4]
Todo:
- [ ] Implementation Filter in Listing via URL parameter 'url/@@project=${project_id}' bei lectures/Lehrveranstaltungen
- [ ] Bereitstellung einer '@@xhr-integrations' view und entsprechendem Link für admin user
- [x] Ajax load link function

Note:

Die EInbindung in die jeweilige Zeilseite *muss* durch den Redakteur erfolgen, indem ein bestimmter vorgefertigter Link an der betreffenden Stelle via copy&paste eingefügt wird. Dies geschieht in jedem FAll via WYSIWYG Editor, d.h. wir planen *keine automatische Implementierung*.

**Comment by bumblebee831** [comment]
Kannst du mir bitte erklären, wie das geht? Ich verstehe deine Anweisung nicht. Welcher Link soll wo via Copy&Paste eingefügt werden?

**Comment by potzenheimer** [comment]
Einfach auf eingeloggt auf Lehrveranstaltungen und den entsprechenden Anweisungen folgen.

**Comment by bumblebee831** [comment]
Aha. Und dann den entsprechenden Link in ein Panel an der entsprechenden Stelle packen. Inhaltstyp Text. Oder?
