### ISSUE TITLE
Filterung nach Drittmittelprokjekten nicht möglich

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/hfph#6]
Nach korrekter Zuweisung eines Drittmittelprojektes zu einer Lehrveranstaltung ist es dennoch nicht möglich, die bei eienr Filterung der Lehrveranstaltungen nach diesem Projekt anzuzeigen.

**Comment by potzenheimer** [comment]
Looks like 'schema.Set' attributes cannot be indexed by plone.indexing - komischerweise haben wir da einen catalog error, der verhindert, dass die Daten tatsächlihc geschrieben werden.

**Comment by potzenheimer** [comment]
A 'set()' causes indexing errors - we could try to convert the value to a string during indexing. Question is wether the database query will still work.

**Comment by potzenheimer** [comment]
Move indexer and use a keyword catalog index - fixed

**Comment by bumblebee831** [comment]
Dasselbe Problem exisitiert immer noch:

E-Mail von Julia: (Ich hatte genau dasselbe Problem)

Liebe Eva,
 
ich habe jetzt Vorlesungen über das Häkchen innerhalb der Lehrveranstaltung zugewiesen und dann anschließend den Code-Schnipsel aus den „Optionen zur asynchronen Integration“ kopiert. Wenn ich diesen dann in eine Seite einfüge (gemacht unter: https://www.hfph.de/forschung/drittmittelprojekte/rottendorf-projekt/zertifikat) wird mir im Editor zwar der Text „Rottendorf Project Listing“ als Link angezeigt, sobald ich die Inhaltseite speichere (und die normale View sehe), wird nichts angezeigt – nicht mal der Link …

**Comment by potzenheimer** [comment]
Der Link wird ersetzt mit den Inhalten der gefilterten View, insofern ist das Verschwinden des Links das erwartete Ergebnis.

Warum ein gesetzter Filter keine Ergebnisse liefert kann ich leider auch nicht sagen - ich werde mal einen catalog reindex machen, um die Datenbank zu bereinigen (dauert ein wenig, aber dann sehen wir weiter)

**Comment by bumblebee831** [comment]
Ok. Danke.
