### ISSUE TITLE
Probleme Inhalte Lehrende

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/hfph#7]
Problem geschildert von Julia:

Liebe Eva,
 
jetzt taucht beim Zugriff von Lehrenden-Dashboards (z.B. Prof. Dr. Michael Reder) ein Problem auf:
Die Links zu den zugewiesenen Lehrveranstaltungen funktionieren tadellos – man landet direkt in der Lecture-Factory … allerdings ist es problematisch bei den anderen Seiten, wo der Lehrende als Contributor hinterlegt ist. Sowohl bei dem Link auf die Lehrenden-Seite kommt eine Fehlermeldung (Nr. 1424949743.510.318230337895), wie auch bei dem Versuch, den Lehrstuhl für Völkerverständigung über das Dashboard anzusteuern (dort Fehler-Nr: 1424949777.450.535310636283). Ebenfalls eine Fehlermeldung kommt, wenn ich mich als Prof. Dr. Wallacher einlogge (Lehrveranstaltungen funktionieren, andere zugewiesene Inhalte über die Contributor-Funktion leider nicht) …
 
Liebe Grüße aus München
 
Julia

**Comment by bumblebee831** [comment]
Julias Antwort nach Test: 

Liebe Eva,
 
jetzt kommt direkt nach dem Einloggen eine Fehlermeldung (ich komme gar nicht auf das Dashboard).
Bei Prof. Reder (1424955511.240.646448329066) und auch bei  Wallacher (1424955573.560.311588930062) …

**Comment by potzenheimer** [comment]
1. ich freue mich, über das "reopen" des Tickets - das ist die korrekte Vorgehensweise im Gegensatz zu 12 Kommentaren zu einem geschlossenen Ticket (das haben wir gestern falsch gemacht)

2. Leider habe ich das Problem schon vor dem erneuten Öffnen des Issues gefixt und somit haben wir uns im vorliegenden Fall überschnitten ;)

**Comment by bumblebee831** [comment]
Ok. Danke

**Comment by bumblebee831** [comment]
Leider nochmal: 

Erneut versucht …
Jetzt geht der Zugriff auf die Lehrenden-Seiten, aber bei beiden Testpersonen werden die Lehrveranstaltungen nicht gefunden (keine Fehlermeldung mit Nummer, sondern der Hinweis, dass die Seite nicht existiert) …
 
Sorry!
 
Liebe Grüße
 
Julia
